apiVersion: v1
# Pod'lara ağ erişimi
kind: Service
metadata:
# Servis'in Kubernetes içindeki adı
  name: proj4-app-service
spec:
  type: NodePort
  selector:
    app: proj4-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007


# Cluster içindeki bir Pod şöyle erişir:
# Servis'in cluster içindeki portu:
  #   http://proj4-app-service:8080

  # targetPort:
  # Pod içindeki "container'ın dinlediği port"

  # NodePort:
  # Dış dünyaya açılan port
  # http://<NodeIP>:30007


  # proj4-app etiketli Pod'ları buluyor
  # 8080 portundan servis ediyor
  # Dış dünyaya 30007 portundan açıyor


